### ISSUE TITLE
Write ModBus adapter

### ISSUE THREAD

**Issue by gcolajan** [ClubCedille/cynergie-data-api#1]
We should fork from this one: https://github.com/gcolajan/modbus-reading

**Comment by mikefaille** [comment]
@gcolajan Aurais-tu besoin que je le fork dans CEDILLE ? 

Pourrais-tu détailler le use case ?

Au plaisir,
Michael

**Comment by gcolajan** [comment]
Non, je pense honnêtement qu'on va "partir" de ce code là, ce n'est plus une divergence mais bien un nouveau projet. Je pourrais faire ça clean et sortir une "lib" du projet mais il n'a pas pour vocation à évoluer en tant que tel donc je pense qu'un copier/coller reste acceptable. Si tu as des suggestions sur comment faire ça propre, j'écoute !

Sinon ça va s'éclaircir avec le détail du reste de l'architecture, qu'est-ce qu'un *adapter* et avec quoi ça communique.

**Comment by mikefaille** [comment]
Pourquoi publier des CSV par http ?

**Comment by gcolajan** [comment]
Ça correspond aux besoins exprimés par la personne utilisant ce système là. Je ne souhaite pas conserver ce mode de distribution pour Cynergie. On peut avoir des CSV, mais pas créés/publiés de la sorte. Si tu as d'autres questions par rapport à modbus-reading je peux t'en parler plus longuement sur le chat.

**Comment by mikefaille** [comment]
Super, je n'ai pas identifié cette personne et l'utilisateur de Cynergie en fait ce n'est pas les étudiants pour qu'ils puissent comprendre comment l'énergie de l'ÉTS est consommé en temps réel ?
