### ISSUE TITLE
Trouver le bon système de DB

### ISSUE THREAD

**Issue by gcolajan** [ClubCedille/cynergie-data-api#3]
Voir le rapport à propos des différents DBMS.

Je propose de partir sur InfluxDB, je souhaiterais vraiment partir sur une TSDB.

On peut aussi envisager une solution cloud, ça pourrait valoir la peine de s'y essayer pour une mise à l'échelle plus facile.

**Comment by mikefaille** [comment]
avec opentsdb tu peux faire scaler ça. Sinon, InfluxDB c'est très bien aussi.

**Comment by mikefaille** [comment]
Prometheus a été choisi.
